### ISSUE TITLE
issue after upgrading to nhibernate5

### ISSUE THREAD

**Issue by jberke** [romis2012/NHibernate.Caches.SysCache3#2]
Trying to upgrade to nhibernate 5.X and getting the following error when my web runs:

Method 'GetAsync' in type 'NHibernate.Caches.SysCache3.SysCacheRegion' from assembly 'NHibernate.Caches.SysCache3, Version=1.0.5.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by igitur** [comment]
@romis2012 TBH, it looks a bit like this project is abandoned, but I would be happy to help. Would you accept pull requests to fix this?
